export const universities = [
  // Major public universities
  "University of Ghana",
  "Kwame Nkrumah University of Science and Technology (KNUST)",
  "University of Cape Coast (UCC)",
  "University of Education, Winneba (UEW)",
  "University for Development Studies (UDS)",
  "University of Mines and Technology (UMaT)",
  "University of Health and Allied Sciences (UHAS)",
  "University of Energy and Natural Resources (UENR)",
  "Ghana Institute of Management and Public Administration (GIMPA)",
  "Ghana Institute of Journalism (GIJ)",
  "National Film and Television Institute (NAFTI)",

  // Major private universities
  "Ashesi University",
  "Valley View University",
  "Central University",
  "Regent University College of Science and Technology",
  "Pentecost University College",
  "Methodist University College Ghana",
  "Wisconsin International University College",
  "Presbyterian University College",
  "Accra Technical University",
  "Koforidua Technical University",
  "Takoradi Technical University",
  "Kumasi Technical University",
  "Sunyani Technical University",
  "Ho Technical University",
  "Cape Coast Technical University",
  "Tamale Technical University",
  
  // Other universities and colleges
  "African University College of Communications",
  "All Nations University College",
  "Catholic University College of Ghana",
  "Christian Service University College",
  "Garden City University College",
  "Ghana Baptist University College",
  "Islamic University College, Ghana",
  "Knutsford University College",
  "Lancaster University, Ghana",
  "Maranatha University College",
  "Radford University College",
  "Webster University Ghana Campus",
];
