

"use client";

import { useState, useRef, useEffect } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import * as z from "zod";
import { Button } from "@/components/ui/button";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Upload, Link as LinkIcon, Youtube, Send, Loader2, Mic, Play, ArrowLeft, BookOpen, FileText, Image as ImageIcon, Globe, ClipboardPaste, ArrowRight, Search, Trash2, Camera, Sparkles } from "lucide-react";
import { interactiveChatWithSources, InteractiveChatWithSourcesInput } from "@/ai/flows/interactive-chat-with-sources";
import { generatePodcastFromSources } from "@/ai/flows/generate-podcast-from-sources";
import { searchWebForSources } from "@/ai/flows/search-web-for-sources";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogDescription } from "@/components/ui/dialog";
import { Checkbox } from "@/components/ui/checkbox";
import Image from "next/image";
import { useToast } from "@/hooks/use-toast";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { cn } from "@/lib/utils";
import { Separator } from "@/components/ui/separator";


const createSpaceSchema = z.object({
    name: z.string().min(1, { message: "Space name is required." }),
    description: z.string().optional(),
});
type CreateSpaceFormSchema = z.infer<typeof createSpaceSchema>;

type Source = {
    type: 'pdf' | 'text' | 'audio' | 'website' | 'youtube' | 'image' | 'clipboard';
    name: string;
    url?: string;
    data?: string; // For file content or copied text
};

type ChatMessage = {
    role: 'user' | 'assistant';
    content: string;
};

type StudySpace = {
    id: number;
    name:string;
    description: string;
    sourceCount: number;
};

type ViewState = 'list' | 'create' | 'edit';

const mockStudySpaces: StudySpace[] = [
    { id: 1, name: "WASSCE Core Maths Prep", description: "All topics for the WASSCE core mathematics exam.", sourceCount: 12 },
    { id: 2, name: "Ghanaian History 1800-1957", description: "From the Ashanti Empire to Independence.", sourceCount: 7 },
    { id: 3, name: "Final Year Project - AI Tutors", description: "Research and resources for my final project on AI in education.", sourceCount: 23 },
    { id: 4, name: "Quantum Physics Basics", description: "Introductory concepts in quantum mechanics.", sourceCount: 5 },
    { id: 5, name: "BECE Social Studies", description: "Revision notes for all BECE social studies topics.", sourceCount: 15 },
    { id: 6, name: "Intro to Python Programming", description: "Basics of Python for beginners.", sourceCount: 10 },
];

const summaryText = "This study space covers the core principles of macroeconomics, including national income, price-level determination, and economic growth. It delves into the functions of money, the role of central banks, and the impact of fiscal and monetary policy on the economy. The sources provide a comprehensive overview of both Keynesian and classical economic theories, supported by real-world examples from the Ghanaian economy. Key topics include inflation, unemployment, aggregate demand and supply, and international trade. This summary is generated by AI to give you a quick overview of the materials you've added.";


export default function StudySpacesPage() {
  const [viewState, setViewState] = useState<ViewState>('list');
  const [sources, setSources] = useState<Source[]>([]);
  const [chatHistory, setChatHistory] = useState<ChatMessage[]>([]);
  const [chatInput, setChatInput] = useState("");
  const [isChatLoading, setIsChatLoading] = useState(false);
  const [isPodcastLoading, setIsPodcastLoading] = useState(false);
  const [podcast, setPodcast] = useState<{ script: string; audio: string } | null>(null);
  
  const [selectedStudySpace, setSelectedStudySpace] = useState<StudySpace | null>(null);
  const [studySpaces, setStudySpaces] = useState<StudySpace[]>(mockStudySpaces);
  const [visibleCount, setVisibleCount] = useState(5);

  const [isAddSourcesOpen, setIsAddSourcesOpen] = useState(false);
  const [isDirty, setIsDirty] = useState(false);
  const { toast } = useToast();

  const [isSummaryExpanded, setIsSummaryExpanded] = useState(false);


  const form = useForm<CreateSpaceFormSchema>({
    resolver: zodResolver(createSpaceSchema),
    defaultValues: { name: "", description: "" },
  });

  const handleShowCreateView = () => {
    setSources([]);
    setViewState('create');
  };
  
  const handleSelectStudySpace = (space: StudySpace) => {
    setSelectedStudySpace(space);
    // In a real app, you would fetch the sources for this space
    setSources([]);
    setChatHistory([]);
    setPodcast(null);
    setViewState('edit');
    setIsDirty(false);
  };

  const handleBackToList = () => {
    setSelectedStudySpace(null);
    setViewState('list');
  };
  
  const handleCreateStudySpace = (name: string, description: string, createdSources: Source[]) => {
    const newSpace: StudySpace = {
        id: Date.now(),
        name,
        description,
        sourceCount: createdSources.length
    };
    setStudySpaces(prev => [newSpace, ...prev]);
    setSelectedStudySpace(newSpace);
    setSources(createdSources);
    setChatHistory([]);
    setPodcast(null);
    setViewState('edit');
  };

  const handleDeleteSource = (indexToDelete: number) => {
    setSources(prev => prev.filter((_, index) => index !== indexToDelete));
    setIsDirty(true);
  };

  const handleAddMoreSources = (newSources: Source[]) => {
    if (newSources.length > 0) {
      setSources(prev => [...prev, ...newSources]);
      setIsDirty(true);
    }
  };

  const handleUpdateStudySpace = () => {
    // In a real app, this would save the changes to the backend.
    console.log("Updating study space with new sources:", sources);
    setIsDirty(false);
    toast({
        title: "Study Space Updated",
        description: `${selectedStudySpace?.name} has been updated.`,
    });
  };

  async function handleChatSubmit() {
    if (!chatInput.trim()) return;
    
    const userMessage: ChatMessage = { role: 'user', content: chatInput };
    setChatHistory(prev => [...prev, userMessage]);
    setIsChatLoading(true);
    setChatInput("");

    try {
        const sourceInputs: InteractiveChatWithSourcesInput['sources'] = sources.map(s => {
            let type: InteractiveChatWithSourcesInput['sources'][0]['type'] = 'website';
            if (s.type === 'pdf' || s.type === 'text' || s.type === 'audio' || s.type === 'youtube' || s.type === 'image') {
                type = s.type;
            }
            return {
                type,
                url: s.url,
                dataUri: s.data,
            };
        });

        const response = await interactiveChatWithSources({
            sources: sourceInputs,
            question: chatInput
        });

        const assistantMessage: ChatMessage = { role: 'assistant', content: response.answer };
        setChatHistory(prev => [...prev, assistantMessage]);
    } catch (e) {
        console.error("Chat error", e);
        const errorMessage: ChatMessage = { role: 'assistant', content: "Sorry, I couldn't process that request." };
        setChatHistory(prev => [...prev, errorMessage]);
    } finally {
        setIsChatLoading(false);
    }
  }

  async function handleGeneratePodcast() {
    setIsPodcastLoading(true);
    setPodcast(null);
    try {
        const sourceUrls = sources.map(s => s.url).filter((url): url is string => !!url);
        const response = await generatePodcastFromSources({ sources: sourceUrls });
        setPodcast({ script: response.podcastScript, audio: response.podcastAudio });
    } catch(e) {
        console.error("Podcast generation error", e);
    } finally {
        setIsPodcastLoading(false);
    }
  }
  
  if (viewState === 'create') {
    return <CreateStudySpaceView onCreate={handleCreateStudySpace} onBack={handleBackToList} />
  }

  if (viewState === 'edit' && selectedStudySpace) {
    return (
        <div className="space-y-8">
            <Button variant="outline" onClick={handleBackToList}>
                <ArrowLeft className="mr-2 h-4 w-4" />
                Back to All Spaces
            </Button>
            <Card>
              <CardHeader>
                  <CardTitle className="text-3xl font-headline font-bold">{selectedStudySpace.name}</CardTitle>
                  <CardDescription className="text-muted-foreground pt-1">{selectedStudySpace.description}</CardDescription>
              </CardHeader>
              <CardContent>
                <Separator className="mb-4" />
                <h3 className="text-xl font-headline font-bold flex items-center gap-2">
                    <Sparkles className="w-5 h-5 text-primary" />
                    AI Summary
                </h3>
                <p className={cn("text-sm text-muted-foreground mt-2", !isSummaryExpanded && "line-clamp-3")}>
                    {summaryText}
                </p>
                <Button variant="link" className="px-0 h-auto mt-2" onClick={() => setIsSummaryExpanded(!isSummaryExpanded)}>
                    {isSummaryExpanded ? "Read Less" : "Read More"}
                </Button>
              </CardContent>
            </Card>

            <Tabs defaultValue="chat" className="w-full">
                <TabsList className="grid w-full grid-cols-3 bg-secondary">
                    <TabsTrigger value="sources">Sources</TabsTrigger>
                    <TabsTrigger value="chat">Chat</TabsTrigger>
                    <TabsTrigger value="generate">Generate</TabsTrigger>
                </TabsList>

                <TabsContent value="sources">
                    <Card>
                        <CardHeader className="flex-row items-center justify-between">
                            <CardTitle>Your Sources ({sources.length})</CardTitle>
                            <Button onClick={() => setIsAddSourcesOpen(true)}>Add More Sources</Button>
                        </CardHeader>
                        <CardContent>
                            {sources.length === 0 ? (
                                <p className="text-sm text-muted-foreground">No sources added yet. Click &quot;Add More Sources&quot; to begin.</p>
                            ) : (
                                <ul className="space-y-2">
                                {sources.map((s, i) => (
                                    <li key={i} className="flex items-start text-sm gap-2 p-2 bg-secondary rounded-md">
                                        {s.type === 'pdf' && <FileText className="w-4 h-4 mt-0.5"/>}
                                        {s.type === 'text' && <FileText className="w-4 h-4 mt-0.5"/>}
                                        {s.type === 'audio' && <Mic className="w-4 h-4 mt-0.5"/>}
                                        {s.type === 'image' && <ImageIcon className="w-4 h-4 mt-0.5"/>}
                                        {s.type === 'website' && <Globe className="w-4 h-4 mt-0.5"/>}
                                        {s.type === 'youtube' && <Youtube className="w-4 h-4 mt-0.5"/>}
                                        {s.type === 'clipboard' && <ClipboardPaste className="w-4 h-4 mt-0.5"/>}
                                        <span className="flex-1 min-w-0 break-words">{s.name}</span>
                                        <Button variant="ghost" size="icon" className="h-6 w-6 ml-auto shrink-0" onClick={() => handleDeleteSource(i)}>
                                            <Trash2 className="w-4 h-4 text-destructive" />
                                        </Button>
                                    </li>
                                ))}
                                </ul>
                            )}
                        </CardContent>
                        <CardFooter>
                            <Button disabled={!isDirty} onClick={handleUpdateStudySpace}>Update Study Space</Button>
                        </CardFooter>
                    </Card>
                </TabsContent>
                
                <TabsContent value="chat">
                    <Card className="h-[600px] flex flex-col mt-6">
                        <CardHeader><CardTitle>Chat with TEMI</CardTitle></CardHeader>
                        <CardContent className="flex-grow overflow-y-auto space-y-4">
                            {chatHistory.length === 0 && (
                                <div className="text-center text-muted-foreground pt-10 px-6">
                                    <BookOpen className="w-12 h-12 mx-auto text-primary/80 mb-4" />
                                    <h3 className="font-semibold text-foreground text-lg">Chat with Your Sources</h3>
                                    <p className="mt-2 text-sm">
                                        Ask me a question and I will answer based solely on the materials you've provided.
                                    </p>
                                    <p className="mt-1 text-xs">
                                        You can even ask for specific citations, like a page from a PDF or a timestamp in a video.
                                    </p>
                                </div>
                            )}
                            {chatHistory.map((msg, i) => (
                                <div key={i} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                                    <div className={`p-3 rounded-lg max-w-[80%] ${msg.role === 'user' ? 'bg-primary text-primary-foreground' : 'bg-secondary'}`}>
                                        <p className="text-sm" dangerouslySetInnerHTML={{__html: msg.content.replace(/\n/g, '<br />')}}/>
                                    </div>
                                </div>
                            ))}
                            {isChatLoading && <div className="flex justify-start"><Loader2 className="h-6 w-6 animate-spin text-primary"/></div>}
                        </CardContent>
                        <div className="p-4 border-t">
                            <div className="relative">
                                <Textarea
                                    value={chatInput}
                                    onChange={(e) => setChatInput(e.target.value)}
                                    placeholder="Ask a question about your sources..."
                                    className="pr-12"
                                    onKeyDown={(e) => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); handleChatSubmit(); }}}
                                    disabled={sources.length === 0 || isChatLoading}
                                />
                                <Button size="icon" className="absolute right-2 top-1/2 -translate-y-1/2 h-8 w-8" onClick={handleChatSubmit} disabled={sources.length === 0 || isChatLoading}>
                                    <Send className="h-4 w-4" />
                                </Button>
                            </div>
                        </div>
                    </Card>
                </TabsContent>

                <TabsContent value="generate">
                   <Card className="h-[600px] flex flex-col items-center justify-center text-center mt-6">
                        <CardContent>
                            {isPodcastLoading ? (
                                <>
                                    <Loader2 className="h-12 w-12 animate-spin text-primary mx-auto" />
                                    <p className="mt-4 text-muted-foreground">Generating your audio overview...</p>
                                </>
                            ) : podcast ? (
                                <div className="space-y-4">
                                    <h3 className="text-xl font-headline">Podcast Ready!</h3>
                                    <audio controls src={podcast.audio} className="w-full"></audio>
                                    <Card className="text-left max-h-80 overflow-y-auto">
                                        <CardHeader><CardTitle>Script</CardTitle></CardHeader>
                                        <CardContent>
                                            <pre className="text-sm whitespace-pre-wrap font-body">{JSON.stringify(JSON.parse(podcast.script), null, 2)}</pre>
                                        </CardContent>
                                    </Card>
                                    <Button onClick={() => setPodcast(null)}>Generate New Podcast</Button>
                                </div>
                            ) : (
                                <>
                                    <Mic className="h-12 w-12 text-primary mx-auto" />
                                    <h3 className="text-xl font-headline mt-4">Generate Audio Overview</h3>
                                    <p className="text-muted-foreground mt-2 max-w-sm mx-auto">Turn your sources into an engaging podcast-style conversation between our AI hosts, Temi & Jay.</p>
                                    <Button size="lg" className="mt-6" onClick={handleGeneratePodcast} disabled={sources.length === 0}>
                                        <Play className="mr-2 h-4 w-4" />
                                        Generate Podcast
                                    </Button>
                                    {sources.length === 0 && <p className="text-xs text-destructive mt-2">Please add at least one source with a URL to generate a podcast.</p>}
                                </>
                            )}
                        </CardContent>
                    </Card>
                </TabsContent>
            </Tabs>
            <AddSourcesDialog open={isAddSourcesOpen} onOpenChange={setIsAddSourcesOpen} onAddSources={handleAddMoreSources} />
        </div>
    )
  }

  return (
    <div className="space-y-8">
      <div className="flex justify-between items-center">
        <div>
            <h1 className="text-3xl font-headline font-bold">Study Spaces</h1>
            <p className="text-muted-foreground mt-1">Create your personal knowledge hub.</p>
        </div>
        <Button onClick={handleShowCreateView}>
            + Create New
        </Button>
      </div>
      <p className="text-muted-foreground bg-secondary p-4 rounded-lg">Upload PDFs, text files, and audio, or add links from websites and YouTube. Then, chat with your AI assistant, TEMI, to get answers and insights based solely on your materials.</p>
      
      <div className="pt-8">
        <h2 className="text-2xl font-headline font-bold mb-4">Your Spaces</h2>
         {studySpaces.length === 0 ? (
            <Card className="flex flex-col items-center justify-center p-12 border-dashed">
                <BookOpen className="w-12 h-12 text-muted-foreground mb-4" />
                <h3 className="text-xl font-semibold text-muted-foreground">No study spaces yet.</h3>
                <p className="text-muted-foreground mb-4">Click the button above to create your first one!</p>
            </Card>
         ) : (
            <>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {studySpaces.slice(0, visibleCount).map(space => (
                        <Card key={space.id} className="cursor-pointer hover:shadow-lg transition-shadow" onClick={() => handleSelectStudySpace(space)}>
                            <CardHeader>
                                <CardTitle>{space.name}</CardTitle>
                                <CardDescription>{space.description}</CardDescription>
                            </CardHeader>
                            <CardContent>
                                <p className="text-sm font-bold text-primary">{space.sourceCount} sources</p>
                            </CardContent>
                        </Card>
                    ))}
                </div>
                {visibleCount < studySpaces.length && (
                    <div className="text-center mt-8">
                        <Button variant="outline" onClick={() => setVisibleCount(prev => prev + 5)}>Load More</Button>
                    </div>
                )}
            </>
         )}
      </div>
    </div>
  );
}


function CreateStudySpaceView({ onCreate, onBack }: { onCreate: (name: string, description: string, sources: Source[]) => void; onBack: () => void; }) {
    const [stage, setStage] = useState<'details' | 'sources'>('details');
    const [spaceDetails, setSpaceDetails] = useState({ name: "", description: "" });
    const { toast } = useToast();

    const detailsForm = useForm<CreateSpaceFormSchema>({
        resolver: zodResolver(createSpaceSchema),
        defaultValues: { name: "", description: "" },
    });

    const [sources, setSources] = useState<Source[]>([]);
    const fileInputRef = useRef<HTMLInputElement>(null);
    const [isTextModalOpen, setIsTextModalOpen] = useState(false);
    const [copiedText, setCopiedText] = useState("");
    const [isUrlModalOpen, setIsUrlModalOpen] = useState(false);
    const [urlModalConfig, setUrlModalConfig] = useState<{type: 'youtube' | 'website', name: string, icon: React.ElementType} | null>(null);
    const [currentUrl, setCurrentUrl] = useState("");
    
    // Web search state
    const [searchQuery, setSearchQuery] = useState("");
    type SourceSearchResult = { title: string; url: string; snippet: string; };
    const [searchResults, setSearchResults] = useState<SourceSearchResult[]>([]);
    const [isSearching, setIsSearching] = useState(false);
    const [isSearchModalOpen, setIsSearchModalOpen] = useState(false);
    const [selectedWebSources, setSelectedWebSources] = useState<SourceSearchResult[]>([]);

    // Camera state
    const [isCameraModalOpen, setIsCameraModalOpen] = useState(false);
    const [hasCameraPermission, setHasCameraPermission] = useState<boolean | null>(null);
    const [capturedImage, setCapturedImage] = useState<string | null>(null);
    const videoRef = useRef<HTMLVideoElement>(null);

    useEffect(() => {
        if (isCameraModalOpen && hasCameraPermission === null) {
            const getCameraPermission = async () => {
                try {
                    const stream = await navigator.mediaDevices.getUserMedia({ video: true });
                    setHasCameraPermission(true);
                    if (videoRef.current) {
                        videoRef.current.srcObject = stream;
                    }
                } catch (error) {
                    console.error('Error accessing camera:', error);
                    setHasCameraPermission(false);
                    toast({
                        variant: 'destructive',
                        title: 'Camera Access Denied',
                        description: 'Please enable camera permissions in your browser settings to use this feature.',
                    });
                }
            };
            getCameraPermission();
        }
    }, [isCameraModalOpen, hasCameraPermission, toast]);

    const handleCapture = () => {
        if (videoRef.current) {
            const canvas = document.createElement('canvas');
            canvas.width = videoRef.current.videoWidth;
            canvas.height = videoRef.current.videoHeight;
            const context = canvas.getContext('2d');
            if (context) {
                context.drawImage(videoRef.current, 0, 0, canvas.width, canvas.height);
                setCapturedImage(canvas.toDataURL('image/jpeg'));
            }
        }
    };

    const handleUsePhoto = () => {
        if (capturedImage) {
            const newSource: Source = {
                type: 'image',
                name: `Captured Image ${new Date().toLocaleString()}.jpg`,
                data: capturedImage
            };
            setSources(prev => [...prev, newSource]);
            handleCloseCameraModal();
        }
    };
    
    const handleCloseCameraModal = () => {
        setCapturedImage(null);
        setIsCameraModalOpen(false);
        if (videoRef.current && videoRef.current.srcObject) {
            const stream = videoRef.current.srcObject as MediaStream;
            stream.getTracks().forEach(track => track.stop());
            videoRef.current.srcObject = null;
        }
        setHasCameraPermission(null);
    };


    const handleDeleteSource = (indexToDelete: number) => {
        setSources(prev => prev.filter((_, index) => index !== indexToDelete));
    };

    const handleFileButtonClick = (accept: string, capture = false) => {
        if (fileInputRef.current) {
            fileInputRef.current.accept = accept;
            if (capture) {
                fileInputRef.current.setAttribute('capture', 'environment');
            } else {
                fileInputRef.current.removeAttribute('capture');
            }
            fileInputRef.current.value = ""; // Reset to allow same file selection
            fileInputRef.current.click();
        }
    };

    const handleOpenUrlModal = (type: 'youtube' | 'website', name: string, icon: React.ElementType) => {
        setUrlModalConfig({ type, name, icon });
        setCurrentUrl("");
        setIsUrlModalOpen(true);
    };

    const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        const file = event.target.files?.[0];
        if (!file) return;

        const reader = new FileReader();
        reader.onload = (e) => {
            const dataUri = e.target?.result as string;

            let fileType: Source['type'] = 'text';

            if (file.type.startsWith('image/')) {
                fileType = 'image';
            } else if (file.type.startsWith('audio/')) {
                fileType = 'audio';
            } else if (file.type === 'application/pdf') {
                fileType = 'pdf';
            }

            const newSource: Source = { type: fileType, name: file.name, data: dataUri };
            setSources(prev => [...prev, newSource]);
        };
        reader.readAsDataURL(file);
    };
    
    const handleAddCopiedText = () => {
        if (!copiedText.trim()) return;
        const newSource: Source = { type: 'clipboard', name: `Pasted Text (${copiedText.substring(0, 15)}...)`, data: copiedText };
        setSources(prev => [...prev, newSource]);
        setCopiedText("");
        setIsTextModalOpen(false);
    };

    const handleAddUrl = () => {
        if (!currentUrl.trim() || !urlModalConfig) return;
        const newSource: Source = { type: urlModalConfig.type, name: currentUrl, url: currentUrl };
        setSources(prev => [...prev, newSource]);
        setCurrentUrl("");
        setIsUrlModalOpen(false);
    };

    const handleSearch = async () => {
        if (!searchQuery.trim()) return;
        setIsSearching(true);
        setSearchResults([]);
        setSelectedWebSources([]);
        setIsSearchModalOpen(true);
        try {
            const response = await searchWebForSources({ query: searchQuery });
            setSearchResults(response.results);
        } catch (e) {
            console.error("Web search failed", e);
            toast({
                variant: 'destructive',
                title: 'Search Failed',
                description: 'Could not fetch web results. Please try again.',
            });
        } finally {
            setIsSearching(false);
        }
    }
    
    const handleAddSelectedSources = () => {
        const newSources: Source[] = selectedWebSources.map(result => {
            const isYoutube = result.url.includes('youtube.com') || result.url.includes('youtu.be');
            return {
                type: isYoutube ? 'youtube' : 'website',
                name: result.title,
                url: result.url
            };
        });

        if (newSources.length > 0) {
            const sourcesToAdd = newSources.filter(ns => 
                !sources.some(s => s.url === ns.url)
            );
            setSources(prev => [...prev, ...sourcesToAdd]);
        }
        setIsSearchModalOpen(false);
    };

    const sourceButtons = [
        { name: "PDF", icon: FileText, action: () => handleFileButtonClick("application/pdf") },
        { name: "Audio", icon: Mic, action: () => handleFileButtonClick("audio/*") },
        { name: "Image", icon: ImageIcon, action: () => handleFileButtonClick("image/*") },
        { name: "Camera", icon: Camera, action: () => setIsCameraModalOpen(true) },
        { name: "Website", icon: Globe, action: () => handleOpenUrlModal('website', 'Website', Globe) },
        { name: "YouTube", icon: Youtube, action: () => handleOpenUrlModal('youtube', 'YouTube', Youtube) },
        { name: "Copied text", icon: ClipboardPaste, action: () => setIsTextModalOpen(true) },
    ];

    const handleNext = (values: CreateSpaceFormSchema) => {
        setSpaceDetails({ name: values.name, description: values.description || "No description." });
        setStage('sources');
    };

    const handleCreate = () => {
        onCreate(spaceDetails.name, spaceDetails.description, sources);
    };

    return (
        <div className="space-y-8">
            <Button variant="outline" onClick={stage === 'details' ? onBack : () => setStage('details')}>
                <ArrowLeft className="mr-2 h-4 w-4" />
                {stage === 'details' ? "Back to All Spaces" : "Back"}
            </Button>
             <Card className="max-w-3xl mx-auto">
                <CardHeader className="text-center">
                    <CardTitle className="text-2xl font-headline">Create a New Study Space</CardTitle>
                    <CardDescription>
                        {stage === 'details' 
                            ? "Step 1 of 2: Give your new space a name and a short description."
                            : "Step 2 of 2: Now, add sources to your study space."
                        }
                    </CardDescription>
                </CardHeader>
                <CardContent className="space-y-8">
                    {stage === 'details' && (
                         <Form {...detailsForm}>
                            <form onSubmit={detailsForm.handleSubmit(handleNext)} className="space-y-6">
                                <FormField control={detailsForm.control} name="name" render={({ field }) => (
                                    <FormItem>
                                        <FormLabel>Study Space Name</FormLabel>
                                        <FormControl><Input placeholder="e.g., The Process of Photosynthesis" {...field} /></FormControl>
                                        <FormMessage />
                                    </FormItem>
                                )}/>
                                <FormField control={detailsForm.control} name="description" render={({ field }) => (
                                    <FormItem>
                                        <FormLabel>Description (optional)</FormLabel>
                                        <FormControl><Textarea placeholder="A short description of what this space is about." {...field} /></FormControl>
                                        <FormMessage />
                                    </FormItem>
                                )}/>
                                <div className="flex justify-end">
                                    <Button type="submit" variant="ghost" className="group">
                                        Next
                                        <ArrowRight className="ml-2 h-4 w-4 transition-transform group-hover:translate-x-1" />
                                    </Button>
                                </div>
                            </form>
                        </Form>
                    )}

                    {stage === 'sources' && (
                        <div className="space-y-8">
                            <div className="space-y-6">
                                <h3 className="font-semibold text-lg text-center">Add Sources</h3>
                                
                                <div className="flex w-full items-center space-x-2">
                                    <Input
                                        placeholder="Search the web for articles, videos..."
                                        value={searchQuery}
                                        onChange={(e) => setSearchQuery(e.target.value)}
                                        onKeyDown={(e) => { if (e.key === 'Enter') { e.preventDefault(); handleSearch(); } }}
                                    />
                                    <Button onClick={handleSearch} disabled={isSearching} size="icon">
                                        <Search className="h-4 w-4" />
                                    </Button>
                                </div>

                                <div className="relative py-2">
                                    <div className="absolute inset-0 flex items-center" aria-hidden="true">
                                        <div className="w-full border-t" />
                                    </div>
                                    <div className="relative flex justify-center">
                                        <span className="bg-card px-2 text-sm text-muted-foreground">
                                            Or Add Manually
                                        </span>
                                    </div>
                                </div>

                                <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                                    {sourceButtons.map(btn => (
                                        <Button key={btn.name} variant="outline" className="h-20 text-base flex-col" onClick={btn.action}><btn.icon className="mb-1 h-6 w-6"/>{btn.name}</Button>
                                    ))}
                                </div>
                                <input type="file" ref={fileInputRef} onChange={handleFileChange} className="hidden" />
                            </div>

                            {sources.length > 0 && (
                                <div className="space-y-2">
                                <h4 className="font-semibold">Added Sources ({sources.length})</h4>
                                <ul className="space-y-2 max-h-60 overflow-y-auto rounded-md border p-2">
                                        {sources.map((s, i) => (
                                            <li key={i} className="flex items-start text-sm gap-2 p-2 bg-secondary rounded-md">
                                                {s.type === 'pdf' && <FileText className="w-4 h-4 mt-0.5"/>}
                                                {s.type === 'text' && <FileText className="w-4 h-4 mt-0.5"/>}
                                                {s.type === 'audio' && <Mic className="w-4 h-4 mt-0.5"/>}
                                                {s.type === 'image' && <ImageIcon className="w-4 h-4 mt-0.5"/>}
                                                {s.type === 'website' && <Globe className="w-4 h-4 mt-0.5"/>}
                                                {s.type === 'youtube' && <Youtube className="w-4 h-4 mt-0.5"/>}
                                                {s.type === 'clipboard' && <ClipboardPaste className="w-4 h-4 mt-0.5"/>}
                                                <span className="flex-1 min-w-0 break-words">{s.name}</span>
                                                <Button variant="ghost" size="icon" className="h-6 w-6 ml-auto shrink-0" onClick={() => handleDeleteSource(i)}>
                                                    <Trash2 className="w-4 h-4 text-destructive" />
                                                </Button>
                                            </li>
                                        ))}
                                </ul>
                                </div>
                            )}
                            
                            <Button onClick={handleCreate} size="lg" className="w-full">Create Study Space</Button>
                        </div>
                    )}
                </CardContent>
            </Card>
            
            <Dialog open={isTextModalOpen} onOpenChange={setIsTextModalOpen}>
                <DialogContent>
                    <DialogHeader><DialogTitle>Add Copied Text</DialogTitle></DialogHeader>
                    <Textarea value={copiedText} onChange={e => setCopiedText(e.target.value)} placeholder="Paste your text here..." rows={10}/>
                    <DialogFooter><Button variant="outline" onClick={() => setIsTextModalOpen(false)}>Cancel</Button><Button onClick={handleAddCopiedText}>Add Text</Button></DialogFooter>
                </DialogContent>
            </Dialog>

            <Dialog open={isUrlModalOpen} onOpenChange={setIsUrlModalOpen}>
                <DialogContent>
                    <DialogHeader><DialogTitle className="flex items-center gap-2">{urlModalConfig && <urlModalConfig.icon className="w-5 h-5" />} Add {urlModalConfig?.name} Link</DialogTitle></DialogHeader>
                    <Input value={currentUrl} onChange={e => setCurrentUrl(e.target.value)} placeholder={urlModalConfig?.type === 'youtube' ? 'https://www.youtube.com/watch?v=...' : 'https://example.com'}/>
                    <DialogFooter><Button variant="outline" onClick={() => setIsUrlModalOpen(false)}>Cancel</Button><Button onClick={handleAddUrl}>Add Link</Button></DialogFooter>
                </DialogContent>
            </Dialog>
            
            <Dialog open={isCameraModalOpen} onOpenChange={handleCloseCameraModal}>
                <DialogContent className="sm:max-w-2xl">
                    <DialogHeader><DialogTitle>Capture from Camera</DialogTitle></DialogHeader>
                    {capturedImage ? (
                        <div className="space-y-4">
                            <Image src={capturedImage} alt="Captured" width={1280} height={720} className="rounded-md" />
                            <div className="flex justify-end gap-2">
                                <Button variant="outline" onClick={() => setCapturedImage(null)}>Retake</Button>
                                <Button onClick={handleUsePhoto}>Use Photo</Button>
                            </div>
                        </div>
                    ) : (
                        <div className="space-y-4">
                            <video ref={videoRef} className="w-full aspect-video rounded-md bg-secondary" autoPlay muted />
                            {hasCameraPermission === false && (
                                <Alert variant="destructive">
                                    <AlertTitle>Camera Access Required</AlertTitle>
                                    <AlertDescription>Please allow camera access to use this feature.</AlertDescription>
                                </Alert>
                            )}
                            <div className="flex justify-end">
                                <Button onClick={handleCapture} disabled={!hasCameraPermission}>Capture</Button>
                            </div>
                        </div>
                    )}
                </DialogContent>
            </Dialog>

            <Dialog open={isSearchModalOpen} onOpenChange={setIsSearchModalOpen}>
                <DialogContent className="sm:max-w-2xl">
                    <DialogHeader>
                        <DialogTitle>Web Search Results</DialogTitle>
                        <DialogDescription>Select the resources you want to add to your study space.</DialogDescription>
                    </DialogHeader>
                    {isSearching ? (
                        <div className="text-center py-10"><Loader2 className="h-8 w-8 animate-spin text-primary mx-auto" /><p className="text-sm text-muted-foreground mt-4">Searching...</p></div>
                    ) : searchResults.length > 0 ? (
                        <div className="space-y-2 max-h-[60vh] overflow-y-auto -mx-6 px-6 border-y">
                            <div className="py-4 space-y-2">
                            {searchResults.map((result, index) => (
                                <div key={index} className="flex items-start space-x-3 p-3 border rounded-md bg-secondary/50">
                                    <Checkbox 
                                        id={`search-result-${index}`}
                                        onCheckedChange={(checked) => {
                                            if (checked) {
                                                setSelectedWebSources(prev => [...prev, result]);
                                            } else {
                                                setSelectedWebSources(prev => prev.filter(r => r.url !== result.url));
                                            }
                                        }}
                                        checked={selectedWebSources.some(s => s.url === result.url)}
                                    />
                                    <div className="grid gap-1.5 leading-none flex-1 min-w-0">
                                        <label htmlFor={`search-result-${index}`} className="font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70 cursor-pointer text-sm">
                                            {result.title}
                                        </label>
                                        <p className="text-xs text-muted-foreground">{result.snippet}</p>
                                        <a href={result.url} target="_blank" rel="noopener noreferrer" className="text-xs text-primary hover:underline truncate">{result.url}</a>
                                    </div>
                                </div>
                            ))}
                            </div>
                        </div>
                    ) : (
                        <div className="text-center py-10 text-muted-foreground">No results found. Try a different search term.</div>
                    )}
                    <DialogFooter>
                        <Button variant="outline" onClick={() => setIsSearchModalOpen(false)}>Cancel</Button>
                        <Button onClick={handleAddSelectedSources}>Add Selected</Button>
                    </DialogFooter>
                </DialogContent>
            </Dialog>
        </div>
    );
}

function AddSourcesDialog({ open, onOpenChange, onAddSources }: { open: boolean; onOpenChange: (open: boolean) => void; onAddSources: (sources: Source[]) => void; }) {
    const [sources, setSources] = useState<Source[]>([]);
    const fileInputRef = useRef<HTMLInputElement>(null);
    const [isTextModalOpen, setIsTextModalOpen] = useState(false);
    const [copiedText, setCopiedText] = useState("");
    const [isUrlModalOpen, setIsUrlModalOpen] = useState(false);
    const [urlModalConfig, setUrlModalConfig] = useState<{type: 'youtube' | 'website', name: string, icon: React.ElementType} | null>(null);
    const [currentUrl, setCurrentUrl] = useState("");
    const { toast } = useToast();
    
    // Web search state
    const [searchQuery, setSearchQuery] = useState("");
    type SourceSearchResult = { title: string; url: string; snippet: string; };
    const [searchResults, setSearchResults] = useState<SourceSearchResult[]>([]);
    const [isSearching, setIsSearching] = useState(false);
    const [isSearchModalOpen, setIsSearchModalOpen] = useState(false);
    const [selectedWebSources, setSelectedWebSources] = useState<SourceSearchResult[]>([]);


    const handleDeleteSource = (indexToDelete: number) => {
        setSources(prev => prev.filter((_, index) => index !== indexToDelete));
    };

    const handleFileButtonClick = (accept: string, capture = false) => {
        if (fileInputRef.current) {
            fileInputRef.current.accept = accept;
            if (capture) {
                fileInputRef.current.setAttribute('capture', 'environment');
            } else {
                fileInputRef.current.removeAttribute('capture');
            }
            fileInputRef.current.value = ""; // Reset to allow same file selection
            fileInputRef.current.click();
        }
    };

    const handleOpenUrlModal = (type: 'youtube' | 'website', name: string, icon: React.ElementType) => {
        setUrlModalConfig({ type, name, icon });
        setCurrentUrl("");
        setIsUrlModalOpen(true);
    };

    const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        const file = event.target.files?.[0];
        if (!file) return;

        const reader = new FileReader();
        reader.onload = (e) => {
            const dataUri = e.target?.result as string;

            let fileType: Source['type'] = 'text';

            if (file.type.startsWith('image/')) {
                fileType = 'image';
            } else if (file.type.startsWith('audio/')) {
                fileType = 'audio';
            } else if (file.type === 'application/pdf') {
                fileType = 'pdf';
            }

            const newSource: Source = { type: fileType, name: file.name, data: dataUri };
            setSources(prev => [...prev, newSource]);
        };
        reader.readAsDataURL(file);
    };
    
    const handleAddCopiedText = () => {
        if (!copiedText.trim()) return;
        const newSource: Source = { type: 'clipboard', name: `Pasted Text (${copiedText.substring(0, 15)}...)`, data: copiedText };
        setSources(prev => [...prev, newSource]);
        setCopiedText("");
        setIsTextModalOpen(false);
    };

    const handleAddUrl = () => {
        if (!currentUrl.trim() || !urlModalConfig) return;
        const newSource: Source = { type: urlModalConfig.type, name: currentUrl, url: currentUrl };
        setSources(prev => [...prev, newSource]);
        setCurrentUrl("");
        setIsUrlModalOpen(false);
    };

    const handleSearch = async () => {
        if (!searchQuery.trim()) return;
        setIsSearching(true);
        setSearchResults([]);
        setSelectedWebSources([]);
        setIsSearchModalOpen(true);
        try {
            const response = await searchWebForSources({ query: searchQuery });
            setSearchResults(response.results);
        } catch (e) {
            console.error("Web search failed", e);
            toast({
                variant: 'destructive',
                title: 'Search Failed',
                description: 'Could not fetch web results. Please try again.',
            });
        } finally {
            setIsSearching(false);
        }
    }

    const handleAddSelectedSources = () => {
        const newSources: Source[] = selectedWebSources.map(result => {
            const isYoutube = result.url.includes('youtube.com') || result.url.includes('youtu.be');
            return {
                type: isYoutube ? 'youtube' : 'website',
                name: result.title,
                url: result.url
            };
        });

        if (newSources.length > 0) {
            const sourcesToAdd = newSources.filter(ns => 
                !sources.some(s => s.url === ns.url)
            );
            setSources(prev => [...prev, ...sourcesToAdd]);
        }
        setIsSearchModalOpen(false);
    };

    const sourceButtons = [
        { name: "PDF", icon: FileText, action: () => handleFileButtonClick("application/pdf") },
        { name: "Audio", icon: Mic, action: () => handleFileButtonClick("audio/*") },
        { name: "Image", icon: ImageIcon, action: () => handleFileButtonClick("image/png, image/jpeg, image/gif, image/webp") },
        { name: "Camera", icon: Camera, action: () => handleFileButtonClick("image/*", true) },
        { name: "Website", icon: Globe, action: () => handleOpenUrlModal('website', 'Website', Globe) },
        { name: "YouTube", icon: Youtube, action: () => handleOpenUrlModal('youtube', 'YouTube', Youtube) },
        { name: "Copied text", icon: ClipboardPaste, action: () => setIsTextModalOpen(true) },
    ];

    const handleDone = () => {
        onAddSources(sources);
        setSources([]); // Clear internal state
        onOpenChange(false);
    };

    return (
        <Dialog open={open} onOpenChange={onOpenChange}>
            <DialogContent className="sm:max-w-3xl h-[90vh] flex flex-col">
                <DialogHeader>
                    <DialogTitle>Add More Sources</DialogTitle>
                    <DialogDescription>
                        Search the web or add files and links. Click &quot;Add to Space&quot; when you&apos;re done.
                    </DialogDescription>
                </DialogHeader>
                <div className="flex-1 overflow-y-auto -mx-6 px-6 space-y-8 border-y py-6">
                    <div className="space-y-6">
                        <div className="flex w-full items-center space-x-2">
                            <Input
                                placeholder="Search the web for articles, videos..."
                                value={searchQuery}
                                onChange={(e) => setSearchQuery(e.target.value)}
                                onKeyDown={(e) => { if (e.key === 'Enter') { e.preventDefault(); handleSearch(); } }}
                            />
                            <Button onClick={handleSearch} disabled={isSearching} size="icon">
                                <Search className="h-4 w-4" />
                            </Button>
                        </div>
                        <div className="relative py-2">
                            <div className="absolute inset-0 flex items-center" aria-hidden="true"><div className="w-full border-t" /></div>
                            <div className="relative flex justify-center"><span className="bg-background px-2 text-sm text-muted-foreground">Or Add Manually</span></div>
                        </div>
                        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                            {sourceButtons.map(btn => (
                                <Button key={btn.name} variant="outline" className="h-20 text-base flex-col" onClick={btn.action}><btn.icon className="mb-1 h-6 w-6"/>{btn.name}</Button>
                            ))}
                        </div>
                        <input type="file" ref={fileInputRef} onChange={handleFileChange} className="hidden" />
                    </div>
                    {sources.length > 0 && (
                        <div className="space-y-2">
                            <h4 className="font-semibold">Sources to Add ({sources.length})</h4>
                            <ul className="space-y-2 max-h-60 overflow-y-auto rounded-md border p-2">
                                {sources.map((s, i) => (
                                    <li key={i} className="flex items-start text-sm gap-2 p-2 bg-secondary rounded-md">
                                        {s.type === 'pdf' && <FileText className="w-4 h-4 mt-0.5"/>} 
                                        {s.type === 'text' && <FileText className="w-4 h-4 mt-0.5"/>} 
                                        {s.type === 'audio' && <Mic className="w-4 h-4 mt-0.5"/>} 
                                        {s.type === 'image' && <ImageIcon className="w-4 h-4 mt-0.5"/>} 
                                        {s.type === 'website' && <Globe className="w-4 h-4 mt-0.5"/>} 
                                        {s.type === 'youtube' && <Youtube className="w-4 h-4 mt-0.5"/>} 
                                        {s.type === 'clipboard' && <ClipboardPaste className="w-4 h-4 mt-0.5"/>}
                                        <span className="flex-1 min-w-0 break-words">{s.name}</span>
                                        <Button variant="ghost" size="icon" className="h-6 w-6 ml-auto shrink-0" onClick={() => handleDeleteSource(i)}><Trash2 className="w-4 h-4 text-destructive" /></Button>
                                    </li>
                                ))}
                            </ul>
                        </div>
                    )}
                </div>
                <DialogFooter>
                    <Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button>
                    <Button onClick={handleDone}>Add to Space</Button>
                </DialogFooter>

                {/* Dialogs for manual adding */}
                <Dialog open={isTextModalOpen} onOpenChange={setIsTextModalOpen}><DialogContent><DialogHeader><DialogTitle>Add Copied Text</DialogTitle></DialogHeader><Textarea value={copiedText} onChange={e => setCopiedText(e.target.value)} placeholder="Paste your text here..." rows={10}/><DialogFooter><Button variant="outline" onClick={() => setIsTextModalOpen(false)}>Cancel</Button><Button onClick={handleAddCopiedText}>Add Text</Button></DialogFooter></DialogContent></Dialog>
                <Dialog open={isUrlModalOpen} onOpenChange={setIsUrlModalOpen}><DialogContent><DialogHeader><DialogTitle className="flex items-center gap-2">{urlModalConfig && <urlModalConfig.icon className="w-5 h-5" />} Add {urlModalConfig?.name} Link</DialogTitle></DialogHeader><Input value={currentUrl} onChange={e => setCurrentUrl(e.target.value)} placeholder={urlModalConfig?.type === 'youtube' ? 'https://www.youtube.com/watch?v=...' : 'https://example.com'}/><DialogFooter><Button variant="outline" onClick={() => setIsUrlModalOpen(false)}>Cancel</Button><Button onClick={handleAddUrl}>Add Link</Button></DialogFooter></DialogContent></Dialog>
                <Dialog open={isSearchModalOpen} onOpenChange={setIsSearchModalOpen}>
                    <DialogContent className="sm:max-w-2xl">
                        <DialogHeader>
                            <DialogTitle>Web Search Results</DialogTitle>
                            <DialogDescription>Select the resources you want to add to your study space.</DialogDescription>
                        </DialogHeader>
                        {isSearching ? (
                            <div className="text-center py-10"><Loader2 className="h-8 w-8 animate-spin text-primary mx-auto" /><p className="text-sm text-muted-foreground mt-4">Searching...</p></div>
                        ) : searchResults.length > 0 ? (
                            <div className="space-y-2 max-h-[60vh] overflow-y-auto -mx-6 px-6 border-y">
                                <div className="py-4 space-y-2">
                                    {searchResults.map((result, index) => (
                                        <div key={index} className="flex items-start space-x-3 p-3 border rounded-md bg-secondary/50">
                                            <Checkbox 
                                                id={`add-search-result-${index}`} 
                                                onCheckedChange={(checked) => {
                                                    if (checked) {
                                                        setSelectedWebSources(prev => [...prev, result]);
                                                    } else {
                                                        setSelectedWebSources(prev => prev.filter(r => r.url !== result.url));
                                                    }
                                                }}
                                                checked={selectedWebSources.some(s => s.url === result.url)}
                                            />
                                            <div className="grid gap-1.5 leading-none flex-1 min-w-0">
                                                <label htmlFor={`add-search-result-${index}`} className="font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70 cursor-pointer text-sm">{result.title}</label>
                                                <p className="text-xs text-muted-foreground">{result.snippet}</p>
                                                <a href={result.url} target="_blank" rel="noopener noreferrer" className="text-xs text-primary hover:underline truncate">{result.url}</a>
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        ) : (
                            <div className="text-center py-10 text-muted-foreground">No results found. Try a different search term.</div>
                        )}
                        <DialogFooter>
                            <Button variant="outline" onClick={() => setIsSearchModalOpen(false)}>Cancel</Button>
                            <Button onClick={handleAddSelectedSources}>Add Selected</Button>
                        </DialogFooter>
                    </DialogContent>
                </Dialog>
            </DialogContent>
        </Dialog>
    )
}
    






    




