import LandingFooter from "@/components/layout/LandingFooter";
import LandingHeader from "@/components/layout/LandingHeader";

export default function TermsOfUsePage() {
  return (
    <div className="flex flex-col min-h-screen bg-background">
      <LandingHeader />
      <main className="flex-grow container mx-auto px-4 md:px-6 py-12">
        <div className="prose dark:prose-invert max-w-4xl mx-auto">
          <h1 className="font-headline">Terms of Use for Learn with Temi</h1>
          <p><strong>Last Updated:</strong> {new Date().toLocaleDateString()}</p>

          <h2>1. Agreement to Terms</h2>
          <p>
            By using our application, Learn with Temi, you agree to be bound by these Terms of Use. If you do not agree to these Terms, do not use the application.
          </p>

          <h2>2. User Accounts</h2>
          <p>
            When you create an account with us, you must provide us with information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service. You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password.
          </p>
          
          <h2>3. User-Provided Content</h2>
          <p>
            You are solely responsible for the content you upload, including documents, links, and other materials ("User Content"). You retain all rights to your User Content, but you grant us a worldwide, non-exclusive, royalty-free license to use, process, and display this content solely for the purpose of providing the services of the application to you. You represent and warrant that you have all the rights, power, and authority necessary to grant the rights granted herein to any User Content that you submit.
          </p>

          <h2>4. AI-Generated Content</h2>
          <p>
            The content generated by our AI, including study notes, podcast scripts, and revision roadmaps, is for educational and informational purposes only. While we strive for accuracy, we make no guarantees about the reliability, accuracy, or completeness of any information provided. You should verify any information obtained from the Service before relying on it.
          </p>

          <h2>5. Use of API Keys</h2>
          <p>
            If you choose to use your personal Gemini API Key, you are responsible for its security and usage. Learn with Temi is not responsible for any charges or issues arising from the use of your personal API key. The key is stored locally on your device and not on our servers.
          </p>

          <h2>6. Monetization and Ads</h2>
          <p>
            The Service is supported by advertising revenue and may display advertisements and promotions from Google AdSense. Some features may require you to watch a rewarded advertisement. The manner, mode, and extent of advertising by Learn with Temi on the Service are subject to change without specific notice to you.
          </p>

          <h2>7. Prohibited Activities</h2>
          <p>
            You agree not to use the Service to:
          </p>
          <ul>
            <li>Upload any content that is illegal, harmful, or infringes on the rights of others.</li>
            <li>Attempt to reverse-engineer, decompile, or otherwise discover the source code of the application.</li>
            <li>Use any automated system to access the service in a manner that sends more request messages to our servers than a human can reasonably produce in the same period by using a conventional on-line web browser.</li>
          </ul>

          <h2>8. Termination</h2>
          <p>
            We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.
          </p>

          <h2>9. Limitation of Liability</h2>
          <p>
            In no event shall Learn with Temi, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
          </p>

          <h2>10. Contact Us</h2>
          <p>
            If you have any questions about these Terms, please contact us at: <a href="mailto:terms@learnwithtemi.com">terms@learnwithtemi.com</a>
          </p>
        </div>
      </main>
      <LandingFooter />
    </div>
  );
}
