
"use client";

import { useState, useEffect, useMemo } from "react";
import { useFirestore } from "@/firebase";
import { doc, setDoc, serverTimestamp } from "firebase/firestore";
import { useDoc } from "@/firebase/firestore/use-doc";
import { Card, CardHeader, CardTitle, CardContent, CardDescription, CardFooter } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import { Loader2 } from "lucide-react";

const initialTermsContent = `## 1. Agreement to Terms
By using our application, Learn with Temi, you agree to be bound by these Terms of Use. If you do not agree to these Terms, do not use the application.

## 2. User Accounts
When you create an account with us, you must provide us with information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service. You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password.

## 3. User-Provided Content
You are solely responsible for the content you upload, including documents, links, and other materials ("User Content"). You retain all rights to your User Content, but you grant us a worldwide, non-exclusive, royalty-free license to use, process, and display this content solely for the purpose of providing the services of the application to you. You represent and warrant that you have all the rights, power, and authority necessary to grant the rights granted herein to any User Content that you submit.

## 4. AI-Generated Content
The content generated by our AI, including study notes, podcast scripts, and revision roadmaps, is for educational and informational purposes only. While we strive for accuracy, we make no guarantees about the reliability, accuracy, or completeness of any information provided. **AI can make mistakes; consider checking important information.** You should verify any information obtained from the Service before relying on it.

## 5. Use of API Keys
If you choose to use your personal Gemini API Key, you are responsible for its security and usage. Learn with Temi is not responsible for any charges or issues arising from the use of your personal API key. The key is stored locally on your device and not on our servers.

## 6. Monetization and Ads
The Service is supported by advertising revenue and may display advertisements and promotions from Google AdSense. Some features may require you to watch a rewarded advertisement. The manner, mode, and extent of advertising by Learn with Temi on the Service are subject to change without specific notice to you.

## 7. Prohibited Activities
You agree not to use the Service to:
- Upload any content that is illegal, harmful, or infringes on the rights of others.
- Attempt to reverse-engineer, decompile, or otherwise discover the source code of the application.
- Use any automated system to access the service in a manner that sends more request messages to our servers than a human can reasonably produce in the same period by using a conventional on-line web browser.

## 8. Termination
We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.

## 9. Limitation of Liability
In no event shall Learn with Temi, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.

## 10. Contact Us
If you have any questions about these Terms, please contact us:
**Next Innovation Africa Ltd**
K209, Nii Amasa Nikoi, CL, New Adenta, GD - 091 – 8790
Phone: [0277777155](tel:0277777155)
Email: [support@learnwithTemi.com](mailto:support@learnwithTemi.com)
Website: [www.learnwithTemi.com](https://www.learnwithTemi.com)
`;

const initialPrivacyContent = `## 1. Introduction
Welcome to Learn with Temi ("we," "our," or "us"). We are committed to protecting your privacy and handling your personal data in an open and transparent manner. This privacy policy explains how we collect, use, disclose, and safeguard your information when you use our application.

## 2. Information We Collect
We may collect information about you in a variety of ways. The information we may collect on the Service includes:
- **Personal Data:** Personally identifiable information, such as your name, and email address, that you voluntarily give to us when you register with the application.
- **Derivative Data:** Information our servers automatically collect when you access the application, such as your IP address, your browser type, your operating system, your access times, and the pages you have viewed directly before and after accessing the application.
- **Data from Social Networks:** User information from social networking sites, such as Google, including your name, your social network username, location, gender, birth date, email address, profile picture, and public data for contacts, if you connect your account to such social networks.
- **User-Provided Content:** We collect the files (PDFs, text, audio) and links (web URLs, YouTube links) you upload or provide to create your StudySpaces. We also collect the exam results you input for AI Assessment.
- **API Keys:** If you choose to provide your own Gemini API Key via the 'Connect Google Student Account' feature, we store this key locally on your device's storage and it is never transmitted to our servers.

## 3. Use of Your Information
Having accurate information about you permits us to provide you with a smooth, efficient, and customized experience. Specifically, we may use information collected about you via the application to:
- Create and manage your account.
- Process your requests and generate AI-powered content (notes, podcasts, roadmaps).
- Email you regarding your account.
- Enable user-to-user communications.
- Monitor and analyze usage and trends to improve your experience with the application.
- Display third-party advertisements through Google AdSense.

## 4. Disclosure of Your Information
We may share information we have collected about you in certain situations. Your information may be disclosed as follows:
- **By Law or to Protect Rights:** If we believe the release of information about you is necessary to respond to legal process, to investigate or remedy potential violations of our policies, or to protect the rights, property, and safety of others, we may share your information as permitted or required by any applicable law, rule, or regulation.
- **Third-Party Service Providers:** We may share your information with third parties that perform services for us or on our behalf, including data analysis, email delivery, hosting services (Firebase), and customer service.
- **Third-Party Advertisers:** We may use third-party advertising companies like Google AdSense to serve ads when you visit the application.

## 5. Security of Your Information
We use administrative, technical, and physical security measures to help protect your personal information. While we have taken reasonable steps to secure the personal information you provide to us, please be aware that despite our efforts, no security measures are perfect or impenetrable, and no method of data transmission can be guaranteed against any interception or other type of misuse.

## 6. Your Rights
You have the right to access, correct, or delete your personal data. You can manage your account information from your user dashboard or by contacting us directly.

## 7. Contact Us
If you have questions or comments about this Privacy Policy, please contact us:
**Next Innovation Africa Ltd**
K209, Nii Amasa Nikoi, CL, New Adenta, GD - 091 – 8790
Phone: [0277777155](tel:0277777155)
Email: [support@learnwithTemi.com](mailto:support@learnwithTemi.com)
Website: [www.learnwithTemi.com](https://www.learnwithTemi.com)
`;


export default function AdminContentPage() {
  const firestore = useFirestore();
  const { toast } = useToast();
  
  const termsRef = useMemo(() => firestore ? doc(firestore, 'legal_content', 'terms_of_use') : null, [firestore]);
  const privacyRef = useMemo(() => firestore ? doc(firestore, 'legal_content', 'privacy_policy') : null, [firestore]);

  const { data: termsData, loading: termsLoading } = useDoc(termsRef);
  const { data: privacyData, loading: privacyLoading } = useDoc(privacyRef);

  const [termsContent, setTermsContent] = useState("");
  const [privacyContent, setPrivacyContent] = useState("");
  const [isSaving, setIsSaving] = useState(false);
  
  useEffect(() => {
    if (termsData) {
      setTermsContent(termsData.content);
    } else if (!termsLoading) {
      setTermsContent(initialTermsContent);
    }
  }, [termsData, termsLoading]);

  useEffect(() => {
    if (privacyData) {
      setPrivacyContent(privacyData.content);
    } else if (!privacyLoading) {
      setPrivacyContent(initialPrivacyContent);
    }
  }, [privacyData, privacyLoading]);

  const handleSaveChanges = async () => {
    if (!firestore || !termsRef || !privacyRef) {
      toast({ variant: 'destructive', title: 'Error', description: 'Could not connect to the database.' });
      return;
    }
    setIsSaving(true);
    try {
      await setDoc(termsRef, { content: termsContent, lastUpdated: serverTimestamp() }, { merge: true });
      await setDoc(privacyRef, { content: privacyContent, lastUpdated: serverTimestamp() }, { merge: true });
      toast({ title: 'Success', description: 'Legal content has been updated.' });
    } catch (error: any) {
      toast({ variant: 'destructive', title: 'Save Failed', description: error.message || 'Could not save changes.' });
    } finally {
      setIsSaving(false);
    }
  };

  const isLoading = termsLoading || privacyLoading;

  return (
    <Card>
      <CardHeader>
        <CardTitle>Legal Content Management</CardTitle>
        <CardDescription>
          Edit the Terms of Use and Privacy Policy for the application. Changes will be live immediately.
        </CardDescription>
      </CardHeader>
      <CardContent>
        {isLoading ? (
            <div className="flex items-center justify-center h-64">
                <Loader2 className="w-8 h-8 animate-spin" />
            </div>
        ) : (
            <Tabs defaultValue="terms">
            <TabsList className="grid w-full grid-cols-2">
                <TabsTrigger value="terms">Terms of Use</TabsTrigger>
                <TabsTrigger value="privacy">Privacy Policy</TabsTrigger>
            </TabsList>
            <TabsContent value="terms" className="mt-4">
                <Textarea value={termsContent} onChange={(e) => setTermsContent(e.target.value)} rows={25} />
            </TabsContent>
            <TabsContent value="privacy" className="mt-4">
                <Textarea value={privacyContent} onChange={(e) => setPrivacyContent(e.target.value)} rows={25} />
            </TabsContent>
            </Tabs>
        )}
      </CardContent>
      <CardFooter>
        <Button onClick={handleSaveChanges} disabled={isSaving || isLoading}>
            {isSaving && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
            Save Changes
        </Button>
      </CardFooter>
    </Card>
  );
}
